<?php
###########################################
# Config file for J-Tracker
# generated by J-Tracker install script
###########################################

# Is J-Tracker installed? 
define('installed', 'yes');

# SQL Settings
define('dbhost', 'localhost');
define('dbuser', 'root');
define('dbpass', '123456');
define('dbname', 'jtracker');

# Site Settings
define('site_logo', '/img/logo.png');
define('site_name', '');

# User Settings
define('avatars_dir', '/files/avatars');

# Localization
define('lang', 'sv');

# Version
define('version', '0.6');

# Modulse system
define('modules_enabled', false);

mysql_connect(dbhost, dbuser, dbpass);
mysql_select_db(dbname) or die("ERROR: An connection was made, however " . dbname . " was not found in the database!");
?>