<?php
###########################################
# Config file for J-Tracker
# generated by J-Tracker install script
###########################################

# Is J-Tracker installed? 
define('installed', true);

# SQL Settings
define('dbhost', 'localhost');
define('dbuser', 'root');
define('dbpass', '');
define('dbname', 'jtracker');

# Site Settings
define('site_logo', '/img/logo.png');
define('site_name', '');

# USer Settings
define('avatars_dir', '/files/avatars');
# Localization
define('lang', 'en');
?>